---
name: docker-publish
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker build
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} 
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} 
      - name: Build and publish
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: joshkaiju/gophernicus:test

