---
name: docker-publish
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker build
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} 
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} 
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: joshkaiju/gophernicus
            #      - name: Build and publish
            #        uses: docker/build-push-action@v4
            #        with:
            #          push: ${{ github.event_name != 'pull_request' }} 
            #          tags: ${{ steps.meta.outputs.tags }}
            #          labels: ${{ steps.meta.outputs.labels }}

